added special treatment for Netflix
Semro/syncwatch pull request #21
Opened 2021-07-28 11:56 UTC by nilshellerhoff

Fixes #20 

I had to add a second content script to inject `netflix.js` into the page header. This was necessary, as content scripts can't normally interact with `window` variables, so `window.netflix` was unavailable. 

Tested in Chrome and Firefox.

2021-07-28 12:31 UTC, nilshellerhoff commented
Nvm, doesn't reliably work with Firefox. Might PR again later

2021-07-28 13:33 UTC, nilshellerhoff commented
I have now switched from CustomEvents to window.postMessage and it now also works in Firefox.

2021-07-28 18:44 UTC, Semro requested changes
Clean up all `console.log()`
Lint and formate code with ESLint and Prettier.
Also, it seems you didn't set up git config [user.name](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git) and [user.email](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address). It's better to set up it for further commits.

2021-07-28 18:44 UTC, Semro commented on plugin/js/content.js
> +  recievedEvent = event.type;
It's already in `fireEvent` function. Why not place it on top of  `fireEvent` and remove it from there.

2021-07-29 05:54 UTC, Semro commented
I don't have Netflix myself to test it, but those changes don't affect other websites and seems Netflix didn't work before, so I merge it.

2021-07-29 05:55 UTC, merged